apiVersion: v1
kind: Service
metadata:
  name: samoim-front-service
  labels:
    app: samoim-front
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: samoim-front
