def label = "bootcamp-${UUID.randomUUID().toString()}"

/* -------- functions ---------- */
/*
def notifySlack(STATUS, COLOR) {
	slackSend (channel: '#bootcamp', color: COLOR, message: STATUS+" : " +  "${env.JOB_NAME} [${env.BUILD_NUMBER}] (${env.BUILD_URL})")
}
*/


/* ------------------------------ */
/*
notifySlack("STARTED", "#FFFF00")
*/


podTemplate(containers: [
    containerTemplate(name: 'maven', image: 'maven:3.8.1-jdk-8', command: 'sleep', args: '99d'),
	containerTemplate(name: "docker", image: "docker:latest", ttyEnabled: true, command: "cat"),
	containerTemplate(name: "kubectl", image: "lachlanevenson/k8s-kubectl", command: "cat", ttyEnabled: true),
	containerTemplate(name: "scanner", image: "newtmitch/sonar-scanner", ttyEnabled: true, command: "cat"),
	containerTemplate(name: 'podman', image: 'ibmcase/podman:ubuntu-16.04', ttyEnabled: true, command: 'cat', privileged: true)    
  ],
  	//volume mount
  volumes: [
		nfsVolume(mountPath: "/root/.m2", serverAddress: '169.56.100.99', serverPath: '/data/srv/nfs/.m2', readOnly: false)
	]
) 
{
	node(POD_LABEL) {
	
		// Git clone from Source Repository.
		stage("Get Source") {
			// Javascript based on Node.js
	 		//git branch: 'main', url: 'https://github.com/happykube/hellonode.git'
			// Java based on Spring Boot, branch : msa
			// 여기에 자신의 gitlab repository의 msa branch로 바꾸세요.
			git branch: 'main', url: 'https://gitlab.com/sa-moim/backend.git'
		} 

		//-- 환경변수 파일 읽어서 변수값 셋팅 
		String stageName = ""
            
		def props = readProperties  file:"deployment/pipeline.properties"
		
		// Docker Hub Info.
		def tag = props["version"]
		def dockerRegistry = props["dockerRegistry"]
		def credentialRegistry=props["credentialRegistry"]
		def image = props["image"]

		// Base Directory
		def baseDir = props["baseDir"]
		def baseDeployDir = props["baseDeployDir"]
        
		// Kubernetes
		def deployment = props["deployment"]
		def config = props["config"]
		def service = props["service"]
		def ingress = props["ingress"]
		def selector_key = props["selector_key"]
		def selector_val = props["selector_val"]
		def namespace = props["namespace"] 

		try {

       			stageName = "Build maven project"

			// Build Source from Repository in gitlab
			stage(stageName) {
				echo "**** START : " + stageName
				def _dir = pwd();
				echo "path : ${_dir}"
				echo "baseDir : ${baseDir}"
				echo "baseDeployDir : ${baseDeployDir}"
				sh "ls -al"
				container('maven') {
						sh "mvn -B -f ${baseDir} clean package -Dmaven.testSkips=true "
						echo "*** RESULT ***"
						sh "pwd"
						sh "ls -al ${baseDir}/target"
				}
			}

			// Code Inspection
			stage("Inspection Code") {
				// container("scanner") {
				// 	sh "sonar-scanner \
				// 		-Dsonar.projectName=hellonode \
				// 		-Dsonar.projectKey=hellonode \
				// 		-Dsonar.sources=. \
				// 		-Dsonar.inclusions=** \
				// 		-Dsonar.language=javascript \
				// 		-Dsonar.host.url=http://sonar.169.56.84.37.nip.io \
				// 		-Dsonar.login=d08b8bde762cfc3ac15dba8aaaa2aa5e030752ad" 
				// }
			} 
			        
			// Build Docker, Push Image to Docker Hub Repository.        
			stage("Build Microservice image") {
				container("podman") {
					withCredentials([usernamePassword(
					                   credentialsId: "${credentialRegistry}",
					                   usernameVariable: 'USER',
					                   passwordVariable: 'PASSWORD'
					               )]) {
					  //sh 'echo user "$USER" pasword "$PASSWORD"'
					  sh "podman login --tls-verify=false --username ${USER} --password ${PASSWORD} ${dockerRegistry}"
						sh "podman build -f ./deployment/Dockerfile -t ${image}:${tag} ."
						sh "podman push ${image}:${tag}"
						sh "podman tag ${image}:${tag} ${image}:dev"
						sh "podman push ${image}:dev"

					}
				}
			}

			
			// Delete Deployment from Cluster in Kubernetes
			stage( "Clean Up Existing Deployments" ) {
				container("kubectl") {
					sh "kubectl delete deployments -n ${namespace} --selector=${selector_key}=${selector_val}"
				}
			}

			// Deploy App to Cluster in Kubernetes

			stage( "Deploy to Cluster" ) {
				check = "k get deployment -n ${namespace} | grep ${deployment} | wc -l"

				container("kubectl") {
					sh "kubectl apply -n ${namespace} -f ${config}"
					if(check > 0) {
						sh "kubectl delete -n ${namespace} -f ${deployment}"
					}
					sh "kubectl apply -n ${namespace} -f ${deployment}"
					sh "sleep 5"
					sh "kubectl apply -n ${namespace} -f ${service}"
					// sh "kubectl apply -n ${namespace} -f ${ingress}"
				}
			}
            echo "**** FINISH ALL STAGES : SUCCESS"
            echo "**** notifySlack"
            //notifySlack("${currentBuild.currentResult}", "#00FF00")
		} catch(e) {
			currentBuild.result = "FAILED"
			//notifySlack("${currentBuild.currentResult}", "#FF0000")
			//notifyMail("${currentBuild.currentResult}", "${email_recipients}")
		}
	}
}
