apiVersion: v1
kind: Service
metadata:
  name: samoim-backend-svc
  labels:
    app: samoim-backend
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: samoim-backend
